### ISSUE TITLE
Problem translating the word "on" in pt-BR.yml

### ISSUE THREAD

**Issue by brunowff** [svenfuchs/i18n#308]
We found an inssue translating de word "on" inside a yml file.

When we translate every other word it work normaly.

Please see this question on stackoverflow:

https://pt.stackoverflow.com/questions/53390/porque-o-caminho-da-tradu%C3%A7%C3%A3o-n%C3%A3o-est%C3%A1-sendo-achado#_=_
brunowff

**Comment by carlosantoniodasilva** [comment]
This is (fortunately or not) how YAML translates the value `on` and `off` to the booleans `true` and `false`.

You can try it in the console without I18n, just loading the yaml file. Using the same content you pasted on the stack overflow question:

```yaml
pt-BR:
  alert_system:
    schedules:
      teste: 'ss'
      every: 'Todo Dia:'
      each: 'A Cada:'
      each_day: 'A Cada #{dias} Dias'
      on: 'Na data:'
```

You can see that by simply loading it using YAML, you get `true=>"Na data:" as key/value, instead of the expected `on`:

```ruby
>> YAML.load_file('x.yml')
=> {"pt-BR"=>{"alert_system"=>{"schedules"=>{"teste"=>"ss", "every"=>"Todo Dia:", "each"=>"A Cada:", "each_day"=>"A Cada \#{dias} Dias", true=>"Na data:"}}}}
```

To workaround that you can quote the word in your YAML file, like this:

```yaml
pt-BR:
  alert_system:
    schedules:
      teste: 'ss'
      every: 'Todo Dia:'
      each: 'A Cada:'
      each_day: 'A Cada #{dias} Dias'
      'on': 'Na data:'
```

That tells YAML to use the value as is, without any "smart parsing", and will give you what you expect:

```ruby
>> YAML.load_file('x.yml')
=> {"pt-BR"=>{"alert_system"=>{"schedules"=>{"teste"=>"ss", "every"=>"Todo Dia:", "each"=>"A Cada:", "each_day"=>"A Cada \#{dias} Dias", "on"=>"Na data:"}}}}
```

The same thing happens for `true/false` and `yes/no`.

Hope that helps.
