### ISSUE TITLE
I18n.translate doesn't use the number.format.separator key to format numbers when a "count" is provided (0.6.11)

### ISSUE THREAD

**Issue by Bastes** [svenfuchs/i18n#328]
Detected using the 0.6.11 version of the gem

To reproduce:

``` yaml
fr:
  number:
    format:
      separator: ","
  some_count:
    other: "%{count} whatever"
```

``` ruby
I18n.translate("some_count", count: 17.5, locale: :fr)
```

Produces "17.5 whatever" instead of "17,5 whatever".

**Comment by travisbell** [comment]
Still seeing this in 0.7.

How is one supposed to get a properly delimited number (using number_to_delimited doesn't seem to work with the singular/plural counts in I18n).

**Comment by radar** [comment]
Thanks @travisbell and @Bastes for letting us know about this. I can verify that I can reproduce this issue.

**Comment by radar** [comment]
One way I can think of accomplishing this is this:

```ruby
def formatted_count(num) do
  "#{number_with_delimiter(num)} #{I18n.t(:some_count, count: num)}"
end
```

Where the `some_count` translation _does not_ include the count:

```yaml
  some_count:
    one: "one"
    many: "many"
    other: "whatever"
```

Looking at the code for interpolation in I18n, it doesn't look like it's going to be easy to special-case what to do in the case of a `count` key.

Therefore I would recommend this solution instead.
