### ISSUE TITLE
Namespace lookup does not include 

### ISSUE THREAD

**Issue by tf** [svenfuchs/i18n#368]
## What I tried to do

Given locales like:

```
en:
  namespace:
    some: "some text"
    other: "other text"

de:
  namespace:
    some "etwas Text" 
```

## What I expected to happen

Looking up a single translation falls back to default locale:

```
I18n.locale = :de
I18n.default_locale = :en
I18n.t('namespace.some') # => "etwas Text"
I18n.t('namespace.other') # => "other text"
```
Looking up a namespace should return the same results as an object:
```
I18n.locale = :de
I18n.default_locale = :en
I18n.t('namespace') # => {some: "etwas Text", other: "other text"}
```

## What actually happened

Since the namespace key is found, fallback logic does not kick in:
```
I18n.locale = :de
I18n.default_locale = :en
I18n.t('namespace') # => {some: "etwas Text"}
```
## Versions of i18n, rails, and anything else you think is neccessary

I18n 0.8.1
Rails 4.2
